version: "3.9"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    volumes:
      - ./timers.db:/app/timers.db
      - ./discord_bot.log:/app/discord_bot.log
    env_file:
      - .env
    restart: unless-stopped

