CREATE TABLE IF NOT EXISTS timers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    ship_name TEXT NOT NULL,
    timer_end TIMESTAMP NOT NULL,
    notified BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS star_notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    username TEXT NOT NULL
);

