name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"

      - name: Deploy with gcloud inside Docker
        run: |
          docker run --rm -v $HOME/.config/gcloud:/root/.config/gcloud google/cloud-sdk:latest \
          gcloud compute ssh my-docker-vm --zone us-east1-b --project estudos-444305 --command "
            cd port-reminder && \
            git pull && \
            sudo docker-compose up -d --build"
